### ISSUE TITLE
swagger-ui-bundle assets are not working

### ISSUE THREAD

**Issue by kornashevskiy-zz** [harmbandstra/swagger-ui-bundle#10] opened 2018-08-14 07:51 UTC
I try to install HBSwaggerUiBundle, all settings from documentaition.
There is my composer.json:
"require": {
       "harmbandstra/swagger-ui-bundle": "^1.0"
},
...
"scripts": {
        "symfony-scripts": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "HarmBandstra\\SwaggerUiBundle\\Composer\\ScriptHandler::linkAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ],
        "post-install-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "HarmBandstra\\SwaggerUiBundle\\Composer\\ScriptHandler::linkAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"

        ],
        "post-update-cmd": [
            "@symfony-scripts"
        ]
    }

and routing.yaml
_swagger-ui:
    resource: '@HBSwaggerUiBundle/Resources/config/routing.yml'
    prefix: /docs
    host: adm.{domain}
    defaults:
        domain: "%domain_default%"
    requirements:
        domain: "%domain_regexp%"

and config.yaml
hb_swagger_ui:
    directory: "%kernel.root_dir%/Resources/docs/"
    files:
        - "swagger.json"

So after composer install i have message from composer that all assets are install

Linked SwaggerUI assets.
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets

 Trying to install assets as relative symbolic links.

 --- ------------------- ------------------ 
      Bundle              Method / Error    
 --- ------------------- ------------------ 
  ✔   SonataCoreBundle    relative symlink  
  ✔   HBSwaggerUiBundle   relative symlink  
  ✔   SonataMediaBundle   relative symlink  
  ✔   AppBundle           relative symlink  
 --- ------------------- ------------------ 

                                                                                
 [OK] All assets were successfully installed.                              

But when i open browser on http://localhost/docs i see in web console this  errors:

adm.loot.loc/:8 GET http://localhost/docs/swagger-ui.css 404 (Not Found)
adm.loot.loc/:70 GET http://localhost/docs/swagger-ui-bundle.js 404 (Not Found)
adm.loot.loc/:71 GET http://localhost/docs/swagger-ui-standalone-preset.js 404 (Not Found)
?url=/docs/file/swagger.json:76 Uncaught ReferenceError: SwaggerUIBundle is not defined
    at window.onload (?url=/docs/file/swagger.json:76) 

I realy dont now what i done wrong and why swagger don`t see all that files.
Please can someone help?

**Comment by harmbandstra** [comment] 2018-08-14 13:06
Which symfony version are you using?

**Comment by kornashevskiy-zz** [comment] 2018-08-14 13:09
3.4

**Comment by harmbandstra** [comment] 2018-08-14 13:12
If you are using php 7+, switch to version "^3.0", if you are using php 5.6, switch to version "^2.0". Then run composer update. Please let me know if that fixes the issue.

**Comment by kornashevskiy-zz** [comment] 2018-08-14 13:31
Now I created symlinks in /web/docs and swagger is working fine, becouse swagger trying load css and js files from http://localhost/docs/swagger-ui.css for example, but during installetion it created symlinks in web/bundles/hbswaggwrui folder. 

Later I will try update version and let you now if that fixes the issue

**Comment by kornashevskiy-zz** [comment] 2018-08-14 14:02
No, updating version didn`t help.

**Comment by harmbandstra** [comment] 2018-12-11 10:14
Since I cannot reproduce this, I'm closing this issue. If you can provide me with an example project to test and reproduce this issue, I will investigate. Thanks.

**Closed as completed by harmbandstra** 2018-12-11 10:14 UTC
